package com.revature.ericschmidt.p1.ticketingapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Event {

	private int EVENT_ID;
	private String EVENT_HEADLINER = new String();
	private String EVENT_SUPP_ACTS = new String();
	private String EVENT_DATE = new String();
	private String EVENT_TIME = new String();
	private double EVENT_FEE;
	private String EVENT_VENUE = new String();

	// Constructor for the Event object below

	public Event() {
		// super();
	}

	/*
	 * public Event(int eVENT_ID, String eVENT_HEADLINER, String eVENT_SUPP_ACTS,
	 * String eVENT_DATE, String eVENT_TIME, double eVENT_FEE, String eVENT_VENUE) {
	 * super(); EVENT_ID = eVENT_ID; EVENT_HEADLINER = eVENT_HEADLINER;
	 * EVENT_SUPP_ACTS = eVENT_SUPP_ACTS; EVENT_DATE = eVENT_DATE; EVENT_TIME =
	 * eVENT_TIME; EVENT_FEE = eVENT_FEE; EVENT_VENUE = eVENT_VENUE; }
	 */

	// Auto generated getters and setters

	public int getEVENT_ID() {
		return EVENT_ID;
	}

	public void setEVENT_ID(int eVENT_ID) {
		EVENT_ID = eVENT_ID;
	}

	public String getEVENT_HEADLINER() {
		return EVENT_HEADLINER;
	}

	public void setEVENT_HEADLINER(String eVENT_HEADLINER) {
		EVENT_HEADLINER = eVENT_HEADLINER;
	}

	public String getEVENT_SUPP_ACTS() {
		return EVENT_SUPP_ACTS;
	}

	public void setEVENT_SUPP_ACTS(String eVENT_SUPP_ACTS) {
		EVENT_SUPP_ACTS = eVENT_SUPP_ACTS;
	}

	public String getEVENT_DATE() {
		return EVENT_DATE;
	}

	public void setEVENT_DATE(String eVENT_DATE) {
		EVENT_DATE = eVENT_DATE;
	}

	public String getEVENT_TIME() {
		return EVENT_TIME;
	}

	public void setEVENT_TIME(String eVENT_TIME) {
		EVENT_TIME = eVENT_TIME;
	}

	public double getEVENT_FEE() {
		return EVENT_FEE;
	}

	public void setEVENT_FEE(double eVENT_FEE) {
		EVENT_FEE = eVENT_FEE;
	}

	public String getEVENT_VENUE() {
		return EVENT_VENUE;
	}

	public void setEVENT_VENUE(String eVENT_VENUE) {
		EVENT_VENUE = eVENT_VENUE;
	}

	// Autogenerated hashCode() method

	@Override
	public int hashCode() {
		return Objects.hash(EVENT_DATE, EVENT_FEE, EVENT_HEADLINER, EVENT_ID, EVENT_SUPP_ACTS, EVENT_TIME, EVENT_VENUE);
	}

	// Autogenerated toEquals() method

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Event other = (Event) obj;
		return Objects.equals(EVENT_DATE, other.EVENT_DATE)
				&& Double.doubleToLongBits(EVENT_FEE) == Double.doubleToLongBits(other.EVENT_FEE)
				&& Objects.equals(EVENT_HEADLINER, other.EVENT_HEADLINER) && EVENT_ID == other.EVENT_ID
				&& Objects.equals(EVENT_SUPP_ACTS, other.EVENT_SUPP_ACTS)
				&& Objects.equals(EVENT_TIME, other.EVENT_TIME) && Objects.equals(EVENT_VENUE, other.EVENT_VENUE);
	}

	// Auto generated to-string method

	@Override
	public String toString() {
		return "Event [EVENT_ID=" + EVENT_ID + ", EVENT_HEADLINER=" + EVENT_HEADLINER + ", EVENT_SUPP_ACTS="
				+ EVENT_SUPP_ACTS + ", EVENT_DATE=" + EVENT_DATE + ", EVENT_TIME=" + EVENT_TIME + ", EVENT_FEE="
				+ EVENT_FEE + ", EVENT_VENUE=" + EVENT_VENUE + "]";
	}

}
