package com.revature.ericschmidt.p1.ticketingapi.model;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "orders")
public class Order {

	@Id
	@Column(name = "ORDER_ID")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "ORDER_ID_SEQ")
	@SequenceGenerator(allocationSize = 1, name = "ORDER_ID_SEQ")
	private int ORDER_ID;
	private int ORDER_COST;

	// Constructor for the Order object below

	public Order() {
		// super();
	}

	/*
	 * public Order(int oRDER_ID, int oRDER_COST) { super(); ORDER_ID = oRDER_ID;
	 * ORDER_COST = oRDER_COST; }
	 */

	// Auto generated getters and setters

	public int getORDER_ID() {
		return ORDER_ID;
	}

	public void setORDER_ID(int oRDER_ID) {
		ORDER_ID = oRDER_ID;
	}

	public int getORDER_COST() {
		return ORDER_COST;
	}

	public void setORDER_COST(int oRDER_COST) {
		ORDER_COST = oRDER_COST;
	}

	// Autogenerated hashCode() method

	@Override
	public int hashCode() {
		return Objects.hash(ORDER_COST, ORDER_ID);
	}

	// Autogenerated toEquals() method

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Order other = (Order) obj;
		return ORDER_COST == other.ORDER_COST && ORDER_ID == other.ORDER_ID;
	}

	// Auto generated to-string method

	@Override
	public String toString() {
		return "Order [ORDER_ID=" + ORDER_ID + ", ORDER_COST=" + ORDER_COST + "]";
	}

}
