package com.revature.ericschmidt.p1.eventapi.model;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "events")
public class Event {

	// Initialize Event object variables below

	@Id
	@Column(name = "EVENTID")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "EVENTID_SEQ")
	@SequenceGenerator(allocationSize = 1, name = "EVENTID_SEQ")
	private int EVENTID;
	@Column(name = "EVENT_HEADLINER", nullable = false)
	private String EVENT_HEADLINER = new String();
	@Column(name = "EVENT_SUPP_ACTS", nullable = true)
	private String EVENT_SUPP_ACTS = new String();
	@Column(name = "EVENT_DATE", nullable = false)
	private String EVENT_DATE = new String();
	@Column(name = "EVENT_TIME", nullable = false)
	private String EVENT_TIME = new String();
	@Column(name = "EVENT_FEE", nullable = true)
	private double EVENT_FEE;
	@Column(name = "EVENT_VENUE", nullable = false)
	private String EVENT_VENUE = new String();

	// Constructor for the Event object below

	public Event() {
		//super();
	}

	/*public Event(int eVENTID, String eVENT_HEADLINER, String eVENT_SUPP_ACTS, String eVENT_DATE, String eVENT_TIME,
			double eVENT_FEE, String eVENT_VENUE) {
		super();
		EVENT_ID = eVENTID;
		EVENT_HEADLINER = eVENT_HEADLINER;
		EVENT_SUPP_ACTS = eVENT_SUPP_ACTS;
		EVENT_DATE = eVENT_DATE;
		EVENT_TIME = eVENT_TIME;
		EVENT_FEE = eVENT_FEE;
		EVENT_VENUE = eVENT_VENUE;
	}*/

	// Auto generated getters and setters

	public int getEVENTID() {
		return EVENTID;
	}

	public void setEVENT_ID(int eVENTID) {
		EVENTID = eVENTID;
	}

	public String getEVENT_HEADLINER() {
		return EVENT_HEADLINER;
	}

	public void setEVENT_HEADLINER(String eVENT_HEADLINER) {
		EVENT_HEADLINER = eVENT_HEADLINER;
	}

	public String getEVENT_SUPP_ACTS() {
		return EVENT_SUPP_ACTS;
	}

	public void setEVENT_SUPP_ACTS(String eVENT_SUPP_ACTS) {
		EVENT_SUPP_ACTS = eVENT_SUPP_ACTS;
	}

	public String getEVENT_DATE() {
		return EVENT_DATE;
	}

	public void setEVENT_DATE(String eVENT_DATE) {
		EVENT_DATE = eVENT_DATE;
	}

	public String getEVENT_TIME() {
		return EVENT_TIME;
	}

	public void setEVENT_TIME(String eVENT_TIME) {
		EVENT_TIME = eVENT_TIME;
	}

	public double getEVENT_FEE() {
		return EVENT_FEE;
	}

	public void setEVENT_FEE(double eVENT_FEE) {
		EVENT_FEE = eVENT_FEE;
	}

	public String getEVENT_VENUE() {
		return EVENT_VENUE;
	}

	public void setEVENT_VENUE(String eVENT_VENUE) {
		EVENT_VENUE = eVENT_VENUE;
	}

	// Autogenerated hashCode() method

	@Override
	public int hashCode() {
		return Objects.hash(EVENT_DATE, EVENT_FEE, EVENT_HEADLINER, EVENTID, EVENT_SUPP_ACTS, EVENT_TIME, EVENT_VENUE);
	}

	// Autogenerated toEquals() method

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Event other = (Event) obj;
		return Objects.equals(EVENT_DATE, other.EVENT_DATE)
				&& Double.doubleToLongBits(EVENT_FEE) == Double.doubleToLongBits(other.EVENT_FEE)
				&& Objects.equals(EVENT_HEADLINER, other.EVENT_HEADLINER) && EVENTID == other.EVENTID
				&& Objects.equals(EVENT_SUPP_ACTS, other.EVENT_SUPP_ACTS)
				&& Objects.equals(EVENT_TIME, other.EVENT_TIME) && Objects.equals(EVENT_VENUE, other.EVENT_VENUE);
	}

	// Auto generated to-string method

	@Override
	public String toString() {
		return "Event [EVENT_ID=" + EVENTID + ", EVENT_HEADLINER=" + EVENT_HEADLINER + ", EVENT_SUPP_ACTS="
				+ EVENT_SUPP_ACTS + ", EVENT_DATE=" + EVENT_DATE + ", EVENT_TIME=" + EVENT_TIME + ", EVENT_FEE="
				+ EVENT_FEE + ", EVENT_VENUE=" + EVENT_VENUE + "]";
	}

}
