package com.revature.ericschmidt.p1.venueapi.model;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "venues")
public class Venue {

	@Id
	@Column(name = "VENUE_ID")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "VENUE_ID_SEQ")
	@SequenceGenerator(allocationSize = 1, name = "VENUE_ID_SEQ")
	private int VENUE_ID;
	@Column(name = "VENUE_NAME", nullable = false)
	private String VENUE_NAME = new String();
	@Column(name = "VENUE_ADDRESS", nullable = false)
	private String VENUE_ADDRESS = new String();
	@Column(name = "VENUE_ZIP", nullable = false)
	private int VENUE_ZIP;
	@Column(name = "VENUE_CAPACITY", nullable = false)
	private int VENUE_CAPACITY;

	// Constructor for the Venue object below

	public Venue() {
		super();
	}

	/*
	 * public Venue(int vENUE_ID, String vENUE_NAME, String vENUE_ADDRESS, int
	 * vENUE_ZIP, int vENUE_CAPACITY) { super(); VENUE_ID = vENUE_ID; VENUE_NAME =
	 * vENUE_NAME; VENUE_ADDRESS = vENUE_ADDRESS; VENUE_ZIP = vENUE_ZIP;
	 * VENUE_CAPACITY = vENUE_CAPACITY; }
	 */

	// Auto generated getters and setters

	public int getVENUE_ID() {
		return VENUE_ID;
	}

	public void setVENUE_ID(int vENUE_ID) {
		VENUE_ID = vENUE_ID;
	}

	public String getVENUE_NAME() {
		return VENUE_NAME;
	}

	public void setVENUE_NAME(String vENUE_NAME) {
		VENUE_NAME = vENUE_NAME;
	}

	public String getVENUE_ADDRESS() {
		return VENUE_ADDRESS;
	}

	public void setVENUE_ADDRESS(String vENUE_ADDRESS) {
		VENUE_ADDRESS = vENUE_ADDRESS;
	}

	public int getVENUE_ZIP() {
		return VENUE_ZIP;
	}

	public void setVENUE_ZIP(int vENUE_ZIP) {
		VENUE_ZIP = vENUE_ZIP;
	}

	public int getVENUE_CAPACITY() {
		return VENUE_CAPACITY;
	}

	public void setVENUE_CAPACITY(int vENUE_CAPACITY) {
		VENUE_CAPACITY = vENUE_CAPACITY;
	}

	// Autogenerated hashCode() method

	@Override
	public int hashCode() {
		return Objects.hash(VENUE_ADDRESS, VENUE_CAPACITY, VENUE_ID, VENUE_NAME, VENUE_ZIP);
	}

	// Autogenerated toEquals() method

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Venue other = (Venue) obj;
		return Objects.equals(VENUE_ADDRESS, other.VENUE_ADDRESS) && VENUE_CAPACITY == other.VENUE_CAPACITY
				&& VENUE_ID == other.VENUE_ID && Objects.equals(VENUE_NAME, other.VENUE_NAME)
				&& VENUE_ZIP == other.VENUE_ZIP;
	}

	// Auto generated to-string method

	@Override
	public String toString() {
		return "Venue [VENUE_ID=" + VENUE_ID + ", VENUE_NAME=" + VENUE_NAME + ", VENUE_ADDRESS=" + VENUE_ADDRESS
				+ ", VENUE_ZIP=" + VENUE_ZIP + ", VENUE_CAPACITY=" + VENUE_CAPACITY + "]";
	}

}
